const { Regex } = require('@companion-module/base');

module.exports = [
  {
    type: 'textinput',
    id: 'ip',
    label: 'Target IP',
tooltip: 'The IP address of the AETA codec',
    width: 6,
    regex: Regex.IP,
    required: true,
  },
  {
    type: 'textinput',
    id: 'port',
    label: 'Target Port',
tooltip: 'The TCP port for AARC protocol (default: 6000)',
    width: 4,
    regex: Regex.PORT,
    default: '6000',
    required: true,
  },
  {
    type: 'textinput',
    id: 'password',
    label: 'AARC Password',
    width: 8,
    default: '',
tooltip: 'Leave blank if no password is set (sends AT#PWD=)',
  },
  {
    type: 'checkbox',
    id: 'enablePolling',
    label: 'Enable Status Polling',
    default: true,
    width: 12,
    disableAutoExpression: true,
  },
  {
    type: 'number',
    id: 'pollingInterval',
    label: 'Status Poll Interval (ms)',
    min: 1000,
    max: 60000,
    default: 5000,
    width: 12,
    isVisibleExpression: '$(options:enablePolling) == true',
  },
  {
    type: 'checkbox',
    id: 'enableVUMeter',
    label: 'Enable VU Meter',
    default: false,
    width: 12,
    disableAutoExpression: true,
  },
  {
    type: 'number',
    id: 'vuMeterInterval',
    label: 'VU Meter Update Interval (ms)',
    tooltip: 'Minimum 150ms, multiple of 50ms',
    min: 150,
    max: 1000,
    default: 150,
    step: 50,
    width: 12,
    isVisibleExpression: '$(options:enableVUMeter) == true',
  },
  {
    type: 'textinput',
    id: 'udpIp',
    label: 'Companion IP (for UDP VU)',
    width: 8,
    regex: Regex.IP,
    isVisibleExpression: '$(options:enableVUMeter) == true',
    tooltip: 'IP address of this computer, where the codec will send UDP packets',
  },
  {
    type: 'textinput',
    id: 'udpPort',
    label: 'UDP Port',
    width: 4,
    regex: Regex.PORT,
    default: '30000',
    isVisibleExpression: '$(options:enableVUMeter) == true',
  },
];