const { Regex } = require('@companion-module/base');

module.exports = [
  {
    type: 'dropdown',
    id: 'model',
    label: 'Codec Model',
    tooltip: 'Select a specific model to filter available actions and variables, or select "All models" to show everything.',
    default: 'auto',
    choices: [
      { id: 'auto', label: 'All models' },
      { id: 'HS3', label: 'HIFISCOOP 3 5AS (HS3)' },
      { id: 'S3', label: 'SCOOP 3 5AS (S3)' },
      { id: 'S4', label: 'SCOOP 4+ (S4)' },
      { id: 'S+', label: 'SCOOPY+ (S+)' },
      { id: 'S5', label: 'SCOOP 5 / SCOOP 5 IP (S5)' },
      { id: 'SxS', label: 'Scoop5 S / Scoop5 S-IP / Scoopy+ S (SxS)' }
    ],
    width: 6,
  },
  {
    type: 'textinput',
    id: 'ip',
    label: 'Target IP',
tooltip: 'The IP address of the AETA codec',
    width: 6,
    regex: Regex.IP,
    required: true,
  },
  {
    type: 'textinput',
    id: 'port',
    label: 'Target Port',
tooltip: 'The TCP port for AARC protocol (default: 6000)',
    width: 4,
    regex: Regex.PORT,
    default: '6000',
    required: true,
  },
  {
    type: 'textinput',
    id: 'password',
    label: 'AARC Password',
    width: 8,
    default: '',
tooltip: 'Leave blank if no password is set (sends AT#PWD=)',
  },
  {
    type: 'checkbox',
    id: 'enablePolling',
    label: 'Enable Status Polling',
    default: true,
    width: 12,
    disableAutoExpression: true,
  },
  {
    type: 'number',
    id: 'pollingInterval',
    label: 'Status Poll Interval (ms)',
    min: 1000,
    max: 60000,
    default: 5000,
    width: 12,
    isVisibleExpression: '$(options:enablePolling) == true',
  },
  {
    type: 'checkbox',
    id: 'enableVUMeter',
    label: 'Enable VU Meter',
    default: false,
    width: 12,
    disableAutoExpression: true,
  },
  {
    type: 'number',
    id: 'vuMeterInterval',
    label: 'VU Meter Update Interval (ms)',
    tooltip: 'Minimum 150ms, multiple of 50ms',
    min: 150,
    max: 1000,
    default: 150,
    step: 50,
    width: 12,
    isVisibleExpression: '$(options:enableVUMeter) == true',
  },
  {
    type: 'textinput',
    id: 'udpIp',
    label: 'Companion IP (for UDP VU)',
    width: 8,
    regex: Regex.IP,
    isVisibleExpression: '$(options:enableVUMeter) == true',
    tooltip: 'IP address of this computer, where the codec will send UDP packets',
  },
  {
    type: 'textinput',
    id: 'udpPort',
    label: 'UDP Port',
    width: 4,
    regex: Regex.PORT,
    default: '30000',
    isVisibleExpression: '$(options:enableVUMeter) == true',
  },
];