module.exports = {
	initVariables() {
	  this.setVariableDefinitions([
		{ variableId: 'connectionStatus', name: 'Connection Status' },
		{ variableId: 'codecModel', name: 'Codec Model' }, // From ATI response
		{ variableId: '5AS', name: '5A System Status' },
		{ variableId: 'codingAlgorithm', name: 'Coding Algorithm' },
		{ variableId: 'networkType', name: 'Network Type' },
		{ variableId: 'ipQuality', name: 'IP Quality' },
		{ variableId: 'packetReplication', name: 'Packet Replication' },
		{ variableId: 'codingBitRate', name: 'Coding Bit Rate' },
		{ variableId: 'ringing', name: 'Ringing Status' },
		{ variableId: 'calling', name: 'Calling Status' },
		{ variableId: 'established', name: 'Established Status' },
		{ variableId: 'released', name: 'Released Status' },
		{ variableId: 'number1', name: 'Dial Number 1' },
		{ variableId: 'number2', name: 'Dial Number 2' },
		{ variableId: 'number3', name: 'Dial Number 3' },
		{ variableId: 'number4', name: 'Dial Number 4' },
		{ variableId: 'number5', name: 'Dial Number 5' },
		{ variableId: 'number6', name: 'Dial Number 6' },
		{ variableId: 'number7', name: 'Dial Number 7' },
		{ variableId: 'number8', name: 'Dial Number 8' },
		{ variableId: 'location1', name: 'Local Number 1' },
		{ variableId: 'location2', name: 'Local Number 2' },
		{ variableId: 'location3', name: 'Local Number 3' },
		{ variableId: 'location4', name: 'Local Number 4' },
		{ variableId: 'location5', name: 'Local Number 5' },
		{ variableId: 'location6', name: 'Local Number 6' },
		{ variableId: 'location7', name: 'Local Number 7' },
		{ variableId: 'location8', name: 'Local Number 8' },
		{ variableId: 'auto1', name: 'Auto Answer 1' },
		{ variableId: 'redundancy1', name: 'Redundancy 1' },
		{ variableId: 'lineConnectionType', name: 'Line Connection Type' },
		{ variableId: 'llbc', name: 'LL Backup Call' },
		{ variableId: 'llbr', name: 'LL Backup Receive' },
		{ variableId: 'frequency', name: 'Coding Frequency' }, // Renamed from 'fre'
		{ variableId: 'syncMode', name: 'AES Sync Mode' }, // New from #SYNC
		{ variableId: 'aesSamplingRate', name: 'AES Sampling Rate' }, // New from #AES
		{ variableId: 'gainIn', name: 'Input Gain' },
		{ variableId: 'gainOut', name: 'Output Gain' },
		{ variableId: 'tae', name: 'Call Filtering' },
		{ variableId: 'hlc', name: 'HLC Enabling' },
		{ variableId: 'nbr', name: 'Redial Retries' },
		{ variableId: 'ttr', name: 'Redial Time' },
		{ variableId: 'dhcp', name: 'DHCP Mode' },
		{ variableId: 'ipAddress', name: 'IP Address' },
		{ variableId: 'ipMask', name: 'IP Mask' },
		{ variableId: 'gateway', name: 'Gateway' },
		{ variableId: 'dns', name: 'DNS' },
		{ variableId: 'configNumber', name: 'Configuration Number' },
		{ variableId: 'testLoop', name: 'Test Loop Status' },
		{ variableId: 'alarmD1', name: 'Alarm Byte 1' },
		{ variableId: 'alarmD2', name: 'Alarm Byte 2' },
		{ variableId: 'alarmD3', name: 'Alarm Byte 3' },
		{ variableId: 'codecStatus', name: 'Codec Status' }, // New from AT#SUP COD1:S=
		{ variableId: 'incomingCall', name: 'Incoming Call' }, // New from AT#SUP ENT:APPEL1=
		{ variableId: 'activeAlarms', name: 'Active Alarms' },
		{ variableId: 'lastError', name: 'Last Error Message' },
		{ variableId: 'audioStatus', name: 'Audio Status' },
		{ variableId: 'jitterBuffer', name: 'Jitter Buffer Status' },
		{ variableId: 'audioLevel', name: 'Audio Level' },
		{ variableId: 'lastConnectedNumber', name: 'Last Connected Number' }
	  ]);
  
	  this.setVariableValues({
		connectionStatus: 'Disconnected',
		codecModel: 'Unknown',
		'5AS': 'Unknown',
		codingAlgorithm: 'Unknown',
		networkType: 'Unknown',
		ipQuality: 'Unknown',
		packetReplication: 'Unknown',
		codingBitRate: 'Unknown',
		ringing: 'False',
		calling: 'False',
		established: 'False',
		released: 'False',
		number1: 'None',
		number2: 'None',
		number3: 'None',
		number4: 'None',
		number5: 'None',
		number6: 'None',
		number7: 'None',
		number8: 'None',
		location1: 'None',
		location2: 'None',
		location3: 'None',
		location4: 'None',
		location5: 'None',
		location6: 'None',
		location7: 'None',
		location8: 'None',
		auto1: 'Off',
		redundancy1: 'Off',
		lineConnectionType: '0',
		llbc: '0',
		llbr: '0',
		frequency: '0',
		syncMode: 'Unknown',
		aesSamplingRate: 'Unknown',
		gainIn: '0',
		gainOut: '0',
		tae: '0',
		hlc: '0',
		nbr: '0',
		ttr: '0',
		dhcp: '0',
		ipAddress: 'None',
		ipMask: 'None',
		gateway: 'None',
		dns: 'None',
		codecStatus: '0', // Idle per AT#SUP
		incomingCall: 'No',
		configNumber: '0',
		testLoop: '0',
		alarmD1: '0',
		alarmD2: '0',
		alarmD3: '0',
		activeAlarms: 'None',
		lastError: '',
		audioStatus: 'Unknown',
		jitterBuffer: '0',
		audioLevel: '0'
	  });
	},
  };